#remote = "pipewire-0"
fps = 60.0
mouse = true
peaks = "auto"
char_set = "default"
theme = "nocolor"
tab = "output"
max_volume_percent = 150.0
enforce_max_volume = false
lazy_capture = false

keybindings = [
 # Exit the program
 { key = { Char = "q" }, action = "Exit" },
 # Toggle mute for the selected item
 { key = { Char = "m" }, action = "ToggleMute" },
 # Make the selected item in Input/Output Devices the default endpoint
 { key = "Enter" , action = "SetDefault" },
  { key = { Char = "`" }, action = { SetAbsoluteVolume = 0.00 } },
 { key = { Char = "1" }, action = { SetAbsoluteVolume = 0.10 } },
 { key = { Char = "2" }, action = { SetAbsoluteVolume = 0.20 } },
 { key = { Char = "3" }, action = { SetAbsoluteVolume = 0.30 } },
 { key = { Char = "4" }, action = { SetAbsoluteVolume = 0.40 } },
 { key = { Char = "5" }, action = { SetAbsoluteVolume = 0.50 } },
 { key = { Char = "6" }, action = { SetAbsoluteVolume = 0.60 } },
 { key = { Char = "7" }, action = { SetAbsoluteVolume = 0.70 } },
 { key = { Char = "8" }, action = { SetAbsoluteVolume = 0.80 } },
 { key = { Char = "9" }, action = { SetAbsoluteVolume = 0.90 } },
 { key = { Char = "0" }, action = { SetAbsoluteVolume = 1.00 } },

 ]